# Generated by Django 3.2.4 on 2021-07-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='discount_total',
        ),
    ]
