# Generated by Django 3.2.4 on 2021-07-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_rename_delivery_cost_order_discount_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='username',
        ),
    ]
